4GeeksAcademy/Proyecto-final_web-Plans

- .gitignore
- src/api/admin.py
- src/api/models.py
Se añaden las tablas: User, Categories, Plans, UserPlans, AssistantPlan. Se han hecho las pruebas con admin en el backend para probar si deja crear todo.
> [Tablas hechas en models]

- src/app.py
app.py: Se ha creado el endpoint tipo POST de Registro y se ha provado en postman.
> [Se ha creado el endpoint de registro]

- src/app.py
app.py: Añadido el endpoint /api/user/profile y pruebas realizadas con postman.
> [Se ha añadido el endpoint de Obtener el perfil del usuario]

- src/app.py
app.py: Añadimos el endpoint para poder eliminar usuarios. 
Probado en postman y comprobaciones hechas.
> [Endpoint DELETE /api/user/profile listo]

- src/app.py
app.py: Creacion de planes lista y probada en postman.
> [Creacion de planes añadidos como Endpoint en app]

- src/app.py
El Endpoint Get para recibir todos los planes existentes esta listo y comprobado en app.py.
> [GET para recibir todos los planes listo]

- src/app.py
app.py: Se añade el endpoint en la app para coger un plan por su id. Se añade tambien opcion par los asistentes activos.
> [Endpoint de Plan individual añadido]

- src/front/js/component/footer.js
- src/front/js/pages/home.js
- src/front/styles/footer.css
- src/front/styles/home.css
He realizado el footer y he arreglado un problema con los estilos del home.
> Terminar footer y solución problema css.

- src/app.py
app.py: Se añade la opcion de cambiar el nombre y el número de personas del plan. 
Pero un condicional para que no puedas cambiar a menos personas de las que hay ya activas.
> [Se ha añadido endpoint de modificar plan]

- src/app.py
app.py: Se ha añadido el Endpoint de delete por id a los planes. 
Las comprobaciones hechas en postman y todo va perfecto.
> [Endpoint de delete de plan por id listo]

- src/app.py
app.py: Se añade endpoint GET de planes activos que tiene el user.
> [Añadido de EndPoint de planes activos]

- .vscode/settings.json
- package-lock.json
- package.json
- src/front/js/layout.js
- src/front/js/pages/home.js
- src/front/js/pages/newPlan.js
- src/front/styles/newPlan.css
- template.html
Creacion de planes: en esta pagina el usuario elige la categoria del plan, nombre, fecha, mumero de personas, localizacion y una pequeña descripcion, tambien conecte con una API "Geocoding API" externa para un autocompletado en el campo "Location" y para la ubicacion en el mapa.
> 12 05   página creando plan fecha hora inicio o hora fin ubicación nombre del plan categoría o asistentes máximos

- src/front/js/component/footer.js
- src/front/js/component/navbar.js
- src/front/js/layout.js
- src/front/js/pages/activePlans.js
- src/front/js/pages/plansHistory.js
- He añadido el navbar y he configurado para que solo se muestre cuando hay token en el localstorage.
- He modificado el footer y algunas páginas del perfil de usuario para que se viera correctamente al final de la páginas.
> Añadido navbar, moficado footer.

- src/api/models.py
- src/app.py
Se crea el Endpoint para que la gente se añada a los planes. 
Se añade el People_Active y Status en la tabla Plan.
People_Active para los usuarios activos en el plan. 
Status para los estados de los planes: Open default.
> [Se añade Endpoint Join y cambios tabla Plan]

- src/app.py
app.py: Endpoint de cambiar estado del plan listo, pero creo que no hace falta añadir este endpoint. 
Hablarlo con el grupo y poder añadir la lógica en la tabla y reemplazar el endpoint
> [Endpoint del cambio de estado hecho]

- src/app.py
app.py: Arreglo del estado del plan segun el horario de españa con el paquete pytz. 
Endpoint del historial de planes acabado según el usuario.
> [Arreglar Endpoint Status y listo Plans/history]

- src/app.py
app.py: Se añaden arreglos a varios endpoints para mejor fluidez.
> [Pequeños arreglos a varios endpoints]

- Pipfile
Pipfile: Dependencias del paquete pytz.
> [Subimos cambios de Pipfile]

- src/front/js/component/footer.js
- src/front/styles/home.css
- Añadí al footer nuestros nombres y el link a los gitHubs personales.
- Modifiqué el css del home por un tamaño de letra que no sea veía como debía.
> He modificado el footer y arreglado un tamaño de letra del home.

- src/app.py
app.py: Cambio al endpoint de Join, no puedes unirte a un plan cerrado. Endpoint de Leave listo para poder salir de un plan.
> [Endpoint de leave y algunos cambios a otros]

- src/app.py
app.py: Añadido de Get de categories para recoger las 5 que habrá pensadas.
> [Endpoint de categories hecho]

- src/app.py
app.py: Añadimos el endpoint para recibir una unica categoria por su id.
> [Endpoint Get Category por id hecho]

- Pipfile.lock
- package-lock.json
- package.json
- src/front/js/component/footer.js
- src/front/js/layout.js
- src/front/js/pages/home.js
- src/front/js/pages/joinPlan.js
- src/front/js/pages/newPlan.js
Esta estará conectada con los planes guardados, en esta pagina el usuario podrá ver toda la información del plan al que quiere unirse, tipo de plan, numero de personas, fecha, hora, ubicación... podrá unirse al plan si el usuario lo desea
> 07   página de apuntarse al plan

- Pipfile
- src/app.py
app.py: Endpoint de Enviar Email y la configuracion
Pipfile.lock: Paquete Flas-Mail
> [Logica del send email hecha]

- src/app.py
- src/templates/emails/welcome_email.html
app.py: Se añade funcionalidad email a la ruta del registro. 
Comprobado en postman y el email llega.
templates/email: Html del email que te llega al correo.
> [Se añade funcionalidad email al Registro]

- src/api/models.py
- src/app.py
- src/templates/emails/join_plan.html
templates: Se cambian colores de los templates y se añade em template de join_plan. 
models.py: Se añade el usuario creador del plan a las tablas. 
app.py: Se modifica el join para añadir la funcionalidad del email. 
También se modifica el post Plans para añadirle auth para que solo puedan crear planes usuarios logeados.
> [Se añade funcionalidad email a Join Plans]

- src/app.py
- src/front/js/component/navbar.js
- src/front/js/layout.js
- src/front/js/pages/home.js
- src/front/js/pages/profile.js
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
app.py: Se da mas vida al token.
navbar: Se arreglan los botones.
home: Se quitan los botones del banner.
profile: Usos de token y arreglos de user
appContext: Usos de token y de login
flux: Arreglos en funciones.
layout: Se arreglan errores.
> [Multiples cambios para arreglar errores criticos]

- src/app.py
- src/front/js/pages/newPlan.js
newPlan: Se añade los id de las categorias.
> [Flujo de añadir plan front a back]

- src/api/models.py
- src/app.py
- src/front/js/component/navbar.js
- src/front/js/layout.js
- src/front/js/pages/logedHome.js
- src/front/js/pages/newPlan.js
- src/front/js/pages/profile.js
- src/front/js/store/flux.js
Arreglo de login, arreglo de creación de planes y arreglo de tablas. 
Ahora Planes tienen el id del creador del plan.
> [Arreglo de errores e incoherencias]

- src/front/js/component/planCard.js
- src/front/js/layout.js
- src/front/js/pages/logedHome.js
- src/front/js/store/flux.js
- He mejorado las card de los planes, ahora sale la ubicación en ellas.
> 29 fujo busqueda con ubicacion

- src/api/models.py
- src/app.py
- src/front/js/layout.js
- src/front/js/pages/activePlans.js
- src/front/js/pages/plansHistory.js
- src/front/js/pages/profile.js
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
Se añade el flujo entre front y back para los planes activos del usuario que ha creado y están abiertos o llenos y a los que se ha unido.
> [Active plans flujo y algunos errores arreglados]

- src/app.py
- src/front/js/pages/newPlan.js
- src/front/js/pages/plansHistory.js
- src/front/js/store/flux.js
app.py: Se arregla endpoint historial.
newPlan: Ahora plan recibe latitud y longitud.
planHistory: Ahora recibe el historial del usuario.
flux: Añadimos al flux el Historial del usuario.
> [Se arreglan varias cosas y flujo historial]

- src/front/js/pages/logedHome.js
Cambio en el componente logedHome.js, la imagen de fondo esta sincronizada con la de perfil, y añadi
un video ejemplo de los tipos de planes al final del componente.
> Cambio en el componente logedHome.js

- src/front/js/component/navbar.js
- src/front/js/component/planCard.js
- src/front/js/layout.js
- src/front/js/pages/logedHome.js
- src/front/js/pages/showPlan.js
- src/front/js/store/flux.js
- src/front/styles/showPlan.css
- He creado la pantalla showPlan para unirse a planes  e hice los cambios necesarios en el flux para su funcionamiento.
- He retocado el navbar.
- He retocado el logedHome para mejorar el mostrado de planes.
> [Crear showPlan y retocado otros componentes.]

- src/api/models.py
- src/app.py
- src/front/js/pages/activePlans.js
- src/front/js/pages/newPlan.js
- src/front/js/pages/plansHistory.js
- src/front/js/store/flux.js
> [Flujo de planes activos, historial e irse]
